# Rustfmt configuration for vmerger-cli

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Function formatting
fn_single_line = false
where_single_line = false

# Control flow formatting
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"

# Comments and documentation
comment_width = 80
doc_comment_code_block_width = 80
format_code_in_doc_comments = true

# String formatting
format_strings = true

# Misc
newline_style = "Unix"
remove_nested_parens = true
reorder_impl_items = true
use_small_heuristics = "Default"

# Unstable features (require nightly)
# unstable_features = true
# format_macro_matchers = true
# format_macro_bodies = true